#!/usr/bin/env python3
# -*- coding: utf8 -*-
'''
	DESCRIPTION
	One stop shopping for all your catalog string needs plus a few extra items.

	⚠️ Every time we bump the catalog, update cat_props=["catalog_version"] below. 

	USAGE:
	• For demo, see any script that calls the catalog e.g. "build_loc_table_feb_2022_stickers.py"
	• catalog_version changes often

	CHANGES
	• 9/15/2021 - new repo, so updated the path to point to "CloudContentAssetsClips"
	• 3/3/2022 - added iso country codes and label uuids (used for filtering elsewhere)
	
	__author__ = "Arlo Emerson <f_emersonjr@apple.com>"
	__version__ = "1.0"
	__date__ = "9/3/2021"
'''

cat_props={
	"catalog_version":"1/2/801",
	"catalog_path":"/Users/ori/CloudContentAssetsClips/Sources/VideoAppsClipsAssets/Catalogs/",
	"catalog_name":"/output_catalog.ccdoc",
	"clips_asset_dir":"/Users/ori/CloudContentAssetsClips/Sources/VideoAppsClipsAssets/Assets",
	"working_dir":"./tmp_output",
}

def print_catalog_properties():
	print("Running this catalog:")
	for c in cat_props:
		print(c + " " + cat_props[c])

def get_catalog_path():
	return cat_props["catalog_path"] + cat_props["catalog_version"] + cat_props["catalog_name"]

def get_catalog_version():
	return cat_props["catalog_version"]

def get_clips_asset_dir():
	return cat_props["clips_asset_dir"]

def get_working_dir():
	return cat_props["working_dir"]

def is_catalog_latest():
	print("TODO: implement sniffer function")

def get_status():
	print("Catalog version: \033[105m" + get_catalog_version() + "\033[0m")

def get_ISO_country_codes():
	list_ISO_country_code_lookup = {
		"AC": "Ascension Island",
		"AD": "Andorra",
		"AE": "United Arab Emirates",
		"AF": "Afghanistan",
		"DZ": "Algeria",
		"AG": "Antigua &amp; Barbuda",
		"AI": "Anguilla",
		"AL": "Albania",
		"AM": "Armenia",
		"AO": "Angola",
		"AQ": "Antarctica",
		"AR": "Argentina",
		"AS": "American Samoa",
		"AT": "Austria",
		"AU": "Australia",
		"AW": "Aruba",
		"AX": "Åland Islands",
		"AZ": "Azerbaijan",
		"BA": "Bosnia &amp; Herzegovina",
		"BB": "Barbados",
		"BD": "Bangladesh",
		"BE": "Belgium",
		"BF": "Burkina Faso",
		"BG": "Bulgaria",
		"BH": "Bahrain",
		"BI": "Burundi",
		"BJ": "Benin",
		"BL": "St. Barthélemy",
		"BM": "Bermuda",
		"BN": "Brunei",
		"BO": "Bolivia",
		"BR": "Brazil",
		"BS": "Bahamas",
		"BT": "Bhutan",
		"BV": "Bouvet Island",
		"BW": "Botswana",
		"BY": "Belarus",
		"BZ": "Belize",
		"CA": "Canada",
		"IC": "Canary Islands",
		"BQ": "Caribbean Netherlands",
		"CC": "Cocos (Keeling) Islands",
		"CD": "Congo - Kinshasa",
		"CF": "Central African Republic",
		"CG": "Congo - Brazzaville",
		"EA": "Ceuta &amp; Melilla",
		"CI": "Côte d’Ivoire",
		"CK": "Cook Islands",
		"CL": "Chile",
		"CM": "Cameroon",
		"CN": "China mainland",
		"CO": "Colombia",
		"CP": "Clipperton Island",
		"CR": "Costa Rica",
		"CU": "Cuba",
		"CV": "Cape Verde",
		"IO": "Chagos Archipelago",
		"CW": "Curaçao",
		"CX": "Christmas Island",
		"TD": "Chad",
		"HR": "Croatia",
		"CY": "Cyprus",
		"CZ": "Czechia",
		"KY": "Cayman Islands",
		"KH": "Cambodia",
		"KM": "Comoros",
		"DG": "Diego Garcia",
		"DJ": "Djibouti",
		"DK": "Denmark",
		"DM": "Dominica",
		"DO": "Dominican Republic",
		"EC": "Ecuador",
		"EE": "Estonia",
		"EG": "Egypt",
		"ER": "Eritrea",
		"SZ": "Eswatini",
		"ET": "Ethiopia",
		"FI": "Finland",
		"FJ": "Fiji",
		"FK": "Falkland Islands",
		"FO": "Faroe Islands",
		"FR": "France",
		"GF": "French Guiana",
		"TF": "French Southern Territories",
		"DE": "Germany",
		"GA": "Gabon",
		"GD": "Grenada",
		"GE": "Georgia",
		"GG": "Guernsey",
		"GH": "Ghana",
		"GI": "Gibraltar",
		"GL": "Greenland",
		"GM": "Gambia",
		"GN": "Guinea",
		"GP": "Guadeloupe",
		"GQ": "Equatorial Guinea",
		"GR": "Greece",
		"GS": "So. Georgia &amp; So. Sandwich Isl.",
		"GT": "Guatemala",
		"GU": "Guam",
		"GW": "Guinea-Bissau",
		"GY": "Guyana",
		"HK": "Hong Kong",
		"HM": "Heard &amp; McDonald Islands",
		"HN": "Honduras",
		"HT": "Haiti",
		"HU": "Hungary",
		"ID": "Indonesia",
		"IE": "Ireland",
		"IL": "Israel",
		"IM": "Isle of Man",
		"IN": "India",
		"IQ": "Iraq",
		"IR": "Iran",
		"IS": "Iceland",
		"IT": "Italy",
		"JE": "Jersey",
		"JM": "Jamaica",
		"JO": "Jordan",
		"JP": "Japan",
		"KE": "Kenya",
		"KG": "Kyrgyzstan",
		"KI": "Kiribati",
		"KN": "St. Kitts &amp; Nevis",
		"KP": "North Korea",
		"KR": "South Korea",
		"KW": "Kuwait",
		"KZ": "Kazakhstan",
		"XK": "Kosovo",
		"LA": "Laos",
		"LB": "Lebanon",
		"LC": "St. Lucia",
		"LI": "Liechtenstein",
		"LR": "Liberia",
		"LS": "Lesotho",
		"LT": "Lithuania",
		"LU": "Luxembourg",
		"LV": "Latvia",
		"LY": "Libya",
		"FM": "Micronesia",
		"MA": "Morocco",
		"MC": "Monaco",
		"MD": "Moldova",
		"ME": "Montenegro",
		"MF": "St. Martin",
		"MG": "Madagascar",
		"MH": "Marshall Islands",
		"MK": "North Macedonia",
		"ML": "Mali",
		"MM": "Myanmar (Burma)",
		"MN": "Mongolia",
		"MO": "Macao",
		"MP": "Northern Mariana Islands",
		"MQ": "Martinique",
		"MR": "Mauritania",
		"MS": "Montserrat",
		"MT": "Malta",
		"MU": "Mauritius",
		"MV": "Maldives",
		"MW": "Malawi",
		"YT": "Mayotte",
		"MX": "Mexico",
		"MY": "Malaysia",
		"MZ": "Mozambique",
		"NA": "Namibia",
		"NC": "New Caledonia",
		"NE": "Niger",
		"NF": "Norfolk Island",
		"NG": "Nigeria",
		"NI": "Nicaragua",
		"NL": "Netherlands",
		"NO": "Norway",
		"NP": "Nepal",
		"NR": "Nauru",
		"NU": "Niue",
		"NZ": "New Zealand",
		"OM": "Oman",
		"PA": "Panama",
		"PE": "Peru",
		"PF": "French Polynesia",
		"PG": "Papua New Guinea",
		"PH": "Philippines",
		"PK": "Pakistan",
		"PL": "Poland",
		"PM": "St. Pierre &amp; Miquelon",
		"PN": "Pitcairn Islands",
		"PR": "Puerto Rico",
		"PS": "Palestinian Territories",
		"PT": "Portugal",
		"PW": "Palau",
		"PY": "Paraguay",
		"QA": "Qatar",
		"RE": "Réunion",
		"RO": "Romania",
		"WS": "Samoa",
		"RS": "Serbia",
		"ES": "Spain",
		"RU": "Russia",
		"RW": "Rwanda",
		"SA": "Saudi Arabia",
		"SB": "Solomon Islands",
		"SC": "Seychelles",
		"LK": "Sri Lanka",
		"SD": "Sudan",
		"SE": "Sweden",
		"SG": "Singapore",
		"SH": "St. Helena",
		"SI": "Slovenia",
		"SJ": "Svalbard &amp; Jan Mayen",
		"SK": "Slovakia",
		"SL": "Sierra Leone",
		"SM": "San Marino",
		"SN": "Senegal",
		"SO": "Somalia",
		"SR": "Suriname",
		"SS": "South Sudan",
		"ST": "São Tomé &amp; Príncipe",
		"SV": "El Salvador",
		"SX": "Sint Maarten",
		"CH": "Switzerland",
		"SY": "Syria",
		"ZA": "South Africa",
		"TA": "Tristan da Cunha",
		"TC": "Turks &amp; Caicos Islands",
		"TG": "Togo",
		"TH": "Thailand",
		"TJ": "Tajikistan",
		"TK": "Tokelau",
		"TL": "Timor-Leste",
		"TM": "Turkmenistan",
		"TN": "Tunisia",
		"TO": "Tonga",
		"TR": "Turkey",
		"TT": "Trinidad &amp; Tobago",
		"TV": "Tuvalu",
		"TW": "Taiwan",
		"TZ": "Tanzania",
		"UA": "Ukraine",
		"UG": "Uganda",
		"GB": "United Kingdom",
		"UM": "U.S. Outlying Islands",
		"US": "United States",
		"UY": "Uruguay",
		"UZ": "Uzbekistan",
		"VA": "Vatican City",
		"VC": "St. Vincent &amp; Grenadines",
		"VE": "Venezuela",
		"VG": "British Virgin Islands",
		"VI": "U.S. Virgin Islands",
		"VN": "Vietnam",
		"VU": "Vanuatu",
		"WF": "Wallis &amp; Futuna",
		"EH": "Western Sahara",
		"YE": "Yemen",
		"ZM": "Zambia",
		"ZW": "Zimbabwe"
	} 
	return list_ISO_country_code_lookup

def get_label_item_UUIDs():
	# leave this alone, it's used to filter out labels from stickers
	label_item_UUIDs = [
		"09C3E628-DB09-4599-BBEE-90F38E53B4C0",
		"5666E2F4-897F-4EF6-BADA-ED813CE45E3D",
		"753CFC9C-6A4D-4089-AB41-A7D1CA7B189D",
		"830EDB3F-87B1-4226-9F8B-9025BCCAAC88",
		"8491CC9E-CB0A-4DF6-8D97-FCF1556179BB",
		"36C59DF6-E8B9-499F-B72B-06B9827625AB",
		"C856C088-4824-4851-A956-97DD01213045",
		"E6CAF0BC-F4DC-4939-B64B-6C4B7F16E2B7",
		"FB3A627B-595F-4CAB-8CC1-090D8BA090EC",
		"7977D35B-532D-406E-90B7-7A5DF3F41F85",
		"7457BD0D-78E3-468F-A875-471AF57D8D34",
		"CFF6F3AE-2E2C-4B47-8E64-ABDA3E719FB3",
		"0F8E213A-E567-40D8-BD13-3465510079C9",
		"8FB036B3-0A22-42A4-9656-AA79A028AD47",
		"2C5057C5-7788-4DAD-8823-CBEC5C57632F",
		"0D1F145B-7313-44AB-BE2E-59659AA68A2F",
		"26E735F1-B54C-42BC-962F-66967082FAA9",
		"86C190A2-34F5-45E7-A623-7F4052E20726",
		"C8A6C7AD-2A9E-4735-B009-282F08AD1DEF",
		"504EC51C-D61E-40D8-B622-DBDFD8F3B553",
		"8A27CFBF-1194-4948-9908-D215BFA11625",
		"6BCC3941-F990-4035-98EF-7192F2CD0872",
		"B7852B30-978E-4720-98D1-EFE530610AE6",
		"83DCC7B8-A2BC-4F23-95A7-01DD072B544B",
		"C87DB8F7-9BA7-40B1-B850-5FEDF236187B",
		"F3140E14-2C79-4420-9ECB-81ED64A7E204",
		"E15646A0-D7B3-432E-A61F-07E0E7CBE099",
		"44EBFB59-2B0E-4C92-BEA7-3540E22B45D4",
		"AA1A7CB3-CB57-4A3B-B725-6754AE237852",
		"81C63419-B0DB-472D-AD01-23F9EDE08A3E",
		"7685C8DD-A1A7-45BF-9087-E4171A1D6ED7",
		"5EF95C26-7B2A-4998-8371-DAC8A181C4A8",
		"7DFDFBD6-C243-48BF-8337-095906591FF5",
		"B729C596-393C-4EA0-8C18-7E68652CB4CA",
		"9961A650-0A8B-4CC1-B120-B7903DFA2489",
		"F19A39BF-5D69-4EA8-9CBC-001806D1C6BB",
		"E9954010-DC95-45B5-B8AF-76AFFCDA67F6",
		"11452512-2982-4CB2-8CEE-FAC481ADED5D"
	]
	return label_item_UUIDs
